development:
  secret_key_base: 68a7da5655426e515e2cdda21c531d673b8d2d214bafd49e49f8ecd5859622bf9d1bcaf4b99e9fb0bfe0742910280901e515530662dc252f7a323b43db6ca6d1
  secret_token: <%= ENV['SECRET_TOKEN'] %>

test:
  secret_key_base: <%= ENV['SECRET_KEY_BASE'] %>
  secret_token: <%= ENV['SECRET_TOKEN'] %>

production:
  secret_key_base: <%= ENV['SECRET_KEY_BASE'] %>
  secret_token: <%= ENV['SECRET_TOKEN'] %>
